name: nmtpy

dependencies:
  - python=3.6
  - cffi
  - cython
  - ipython
  - pyyaml
  - six
  - numpy
  - scipy
  - scikit-learn
  - tqdm
  - pillow
  - pip:
    - torch==1.3.1
    - torchvision==0.4.2
    - sacrebleu>=1.2.9
    - editdistance==0.4
    - subword_nmt==0.3.5
    - ipdb
    - -e .
